import type { SyncEntityType } from '../syncTypes';
import type { SyncEntityDefinition } from './syncEntity.types';

const metadata = ['id', 'owner_user_id', 'remote_id', 'sync_status', 'sync_error', 'last_synced_at', 'updated_at', 'deleted_at'];

export const syncEntityRegistry: Record<SyncEntityType, SyncEntityDefinition> = {
  exercises: { entityType: 'exercises', localTable: 'exercises', deletionStrategy: 'tombstone', fields: [...metadata, 'name', 'source', 'category', 'movement_pattern', 'target_muscle', 'secondary_muscle', 'equipment', 'difficulty', 'notes'] },
  workoutSessions: { entityType: 'workoutSessions', localTable: 'workout_sessions', deletionStrategy: 'tombstone', fields: [...metadata, 'group_id', 'plan_id', 'plan_cycle_id', 'plan_day_id', 'phase_id', 'date', 'week', 'weekday', 'title', 'status', 'training_mode', 'recorded_by_user_id', 'source_device_id', 'started_at', 'finished_at', 'created_at'] },
  workoutExerciseRecords: { entityType: 'workoutExerciseRecords', localTable: 'workout_exercise_records', deletionStrategy: 'tombstone', fields: [...metadata, 'session_id', 'plan_exercise_id', 'exercise_id', 'order_index', 'replaced_from_exercise_id', 'priority', 'planned_sets', 'planned_reps', 'planned_rep_min', 'planned_rep_max', 'planned_rpe', 'planned_rir', 'planned_percent_1rm', 'planned_rest_seconds', 'notes'] },
  workoutSets: { entityType: 'workoutSets', localTable: 'workout_sets', deletionStrategy: 'tombstone', fields: [...metadata, 'session_id', 'exercise_record_id', 'member_id', 'set_number', 'recorded_by_user_id', 'source_device_id', 'planned_weight', 'actual_weight', 'planned_reps', 'actual_reps', 'rpe', 'rir', 'actual_rest_seconds', 'completed', 'skipped', 'notes', 'created_at'] },
  trainingPlans: { entityType: 'trainingPlans', localTable: 'plan_templates', deletionStrategy: 'tombstone', fields: [...metadata, 'name', 'creator_id', 'visibility', 'goal', 'duration_weeks', 'frequency_per_week', 'description', 'source', 'origin_scheme_id', 'version', 'status', 'created_at'] },
  planCycles: { entityType: 'planCycles', localTable: 'plan_cycles', deletionStrategy: 'tombstone', fields: [...metadata, 'group_id', 'plan_id', 'cycle_index', 'name', 'start_date', 'end_date', 'planned_weeks', 'actual_start_date', 'actual_end_date', 'status', 'completed_at', 'archived_at', 'created_at'] },
  planCycleSummaries: { entityType: 'planCycleSummaries', localTable: 'plan_cycle_summaries', deletionStrategy: 'tombstone', fields: [...metadata, 'group_id', 'plan_id', 'plan_cycle_id', 'planned_workout_count', 'completed_workout_count', 'skipped_workout_count', 'completion_rate', 'total_volume', 'total_sets', 'total_reps', 'total_duration_seconds', 'estimated_calories', 'top_progress_exercises_json', 'weak_exercises_json', 'muscle_group_distribution_json', 'summary_text', 'created_at'] },
  planPhases: { entityType: 'planPhases', localTable: 'plan_phases', deletionStrategy: 'tombstone', fields: [...metadata, 'plan_id', 'name', 'type', 'start_week', 'end_week', 'order_index', 'created_at'] },
  planDays: { entityType: 'planDays', localTable: 'plan_days', deletionStrategy: 'tombstone', fields: [...metadata, 'plan_id', 'phase_id', 'week', 'weekday', 'title', 'focus', 'notes', 'created_at'] },
  planExercises: { entityType: 'planExercises', localTable: 'plan_exercises', deletionStrategy: 'tombstone', fields: [...metadata, 'plan_day_id', 'exercise_id', 'priority', 'order_index', 'sets', 'reps', 'rep_min', 'rep_max', 'intensity_type', 'percent_1rm', 'rpe_target', 'rir_target', 'fixed_weight', 'reference_lift', 'rest_seconds', 'progression_rule_id', 'notes', 'created_at'] },
  trainingReports: { entityType: 'trainingReports', localTable: 'training_reports', deletionStrategy: 'tombstone', fields: [...metadata, 'group_id', 'member_id', 'plan_id', 'plan_cycle_id', 'workout_session_id', 'report_date', 'duration_seconds', 'total_volume', 'total_sets', 'total_reps', 'exercise_count', 'estimated_calories', 'estimated_calories_low', 'estimated_calories_high', 'intensity_level', 'muscle_group_summary_json', 'exercise_summary_json', 'personal_records_json', 'notes', 'created_at'] },
  trainingReminders: { entityType: 'trainingReminders', localTable: 'training_reminders', deletionStrategy: 'tombstone', fields: [...metadata, 'group_id', 'plan_id', 'plan_cycle_id', 'type', 'enabled', 'weekday', 'remind_time', 'minutes_before', 'timezone', 'title_template', 'body_template', 'last_scheduled_at', 'last_fired_at', 'created_at'] },
  groups: { entityType: 'groups', localTable: 'groups', deletionStrategy: 'dedicated-endpoint', fields: [...metadata, 'name', 'active_plan_id', 'current_phase_type', 'current_week', 'friday_enabled', 'friday_strategy', 'created_at'] },
  groupMembers: { entityType: 'groupMembers', localTable: 'group_members', deletionStrategy: 'dedicated-endpoint', fields: [...metadata, 'group_id', 'display_name', 'user_id', 'member_type', 'local_member_id', 'role', 'avatar_url', 'joined_at', 'created_at'] },
  memberProfiles: { entityType: 'memberProfiles', localTable: 'member_profiles', deletionStrategy: 'dedicated-endpoint', fields: [...metadata, 'member_id', 'group_id', 'avatar_url', 'avatar_thumb_url', 'avatar_local_uri', 'avatar_updated_at', 'bodyweight', 'bench_1rm', 'squat_1rm', 'deadlift_1rm', 'overhead_press_1rm', 'pullup_reference_weight', 'barbell_increment', 'dumbbell_increment', 'created_at'] },
  bodyMetrics: { entityType: 'bodyMetrics', localTable: 'body_metrics', deletionStrategy: 'tombstone', fields: [...metadata, 'member_id', 'date', 'weight_kg', 'body_fat_percent', 'chest_cm', 'waist_cm', 'hip_cm', 'bicep_cm', 'thigh_cm', 'calf_cm', 'notes', 'created_at'] },
  bodyMetricGoals: { entityType: 'bodyMetricGoals', localTable: 'body_metric_goals', deletionStrategy: 'tombstone', fields: [...metadata, 'member_id', 'goal_type', 'target_weight_kg', 'target_date', 'notes', 'created_at'] },
  recoveryLogs: { entityType: 'recoveryLogs', localTable: 'recovery_logs', deletionStrategy: 'tombstone', fields: [...metadata, 'member_id', 'date', 'sleep_score', 'appetite_score', 'motivation_score', 'soreness_score', 'joint_pain_score', 'fatigue_score', 'total_score', 'recommendation', 'created_at'] },
  progressionSuggestions: { entityType: 'progressionSuggestions', localTable: 'progression_suggestions', deletionStrategy: 'tombstone', fields: [...metadata, 'member_id', 'exercise_id', 'session_id', 'suggestion', 'suggested_weight', 'reason', 'created_at'] },
  settings: { entityType: 'settings', localTable: 'user_preferences', deletionStrategy: 'overwrite', fields: [...metadata, 'weight_unit', 'default_record_target', 'default_training_mode', 'weight_increment', 'rest_timer_enabled', 'effort_display', 'created_at'] },
};

export function getSyncEntityDefinition(entityType: SyncEntityType): SyncEntityDefinition {
  return syncEntityRegistry[entityType];
}
